// GENERATED by scripts/gen-icons.mjs — do not edit.
import type { ReactElement, SVGProps } from "react";
import { FileTextIcon } from "./FileTextIcon";
import { GlobeIcon } from "./GlobeIcon";
import { NextIcon } from "./NextIcon";
import { TurborepoIcon } from "./TurborepoIcon";
import { VercelIcon } from "./VercelIcon";
import { WindowIcon } from "./WindowIcon";

export { FileTextIcon } from "./FileTextIcon";
export { GlobeIcon } from "./GlobeIcon";
export { NextIcon } from "./NextIcon";
export { TurborepoIcon } from "./TurborepoIcon";
export { VercelIcon } from "./VercelIcon";
export { WindowIcon } from "./WindowIcon";

export const iconNames = ["file-text", "globe", "next", "turborepo", "vercel", "window"] as const;
export type IconName = (typeof iconNames)[number];

export type IconComponent = (props: SVGProps<SVGSVGElement>) => ReactElement;

export const icons: Record<IconName, IconComponent> = {
  "file-text": FileTextIcon,
  "globe": GlobeIcon,
  "next": NextIcon,
  "turborepo": TurborepoIcon,
  "vercel": VercelIcon,
  "window": WindowIcon,
};
