// GENERATED by scripts/gen-icons.mjs from raw/icons/vercel.svg — do not edit.
import type { SVGProps } from "react";

export const VercelIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
<g clipPath="url(#clip0_977_547)">
<path fillRule="evenodd" clipRule="evenodd" d="M10.5 3L18.5 17H2.5L10.5 3Z" fill="currentColor"/>
</g>
<defs>
<clipPath id="clip0_977_547">
<rect width="16" height="16" fill="currentColor" transform="translate(2.5 2)"/>
</clipPath>
</defs>
</svg>
);
